/* Generated by re2c 0.13.5 on Mon Nov 04 20:23:24 2013 */
#line 1 "lexer.re.cpp"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "lexer.h"

TokenType scan(const char*& p)
{
	const char* yymarker;
initial:

#line 15 "lexer.cpp"
	{
		unsigned char yych;

		yych = (unsigned char)*p;
		switch (yych) {
		case 0x00:	goto yy61;
		case '\t':
		case '\v':
		case '\f':
		case ' ':	goto yy67;
		case '\n':	goto yy69;
		case '!':	goto yy24;
		case '%':	goto yy10;
		case '&':	goto yy14;
		case '(':	goto yy34;
		case ')':	goto yy36;
		case '*':	goto yy6;
		case '+':	goto yy2;
		case ',':	goto yy28;
		case '-':	goto yy4;
		case '/':	goto yy8;
		case '0':	goto yy65;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy63;
		case ':':	goto yy30;
		case ';':	goto yy32;
		case '<':	goto yy18;
		case '=':	goto yy22;
		case '>':	goto yy20;
		case '?':	goto yy26;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'T':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'u':
		case 'x':
		case 'y':
		case 'z':	goto yy66;
		case 'S':	goto yy46;
		case 'U':	goto yy48;
		case '[':	goto yy38;
		case ']':	goto yy40;
		case '^':	goto yy16;
		case 'b':	goto yy56;
		case 'c':	goto yy55;
		case 'd':	goto yy52;
		case 'e':	goto yy51;
		case 'f':	goto yy54;
		case 'g':	goto yy49;
		case 'i':	goto yy50;
		case 'r':	goto yy57;
		case 's':	goto yy58;
		case 't':	goto yy60;
		case 'v':	goto yy59;
		case 'w':	goto yy53;
		case '{':	goto yy42;
		case '|':	goto yy12;
		case '}':	goto yy44;
		default:	goto yy71;
		}
yy2:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '+':	goto yy225;
		case '=':	goto yy223;
		default:	goto yy3;
		}
yy3:
#line 51 "lexer.re.cpp"
		{ return TokenType::Add; }
#line 124 "lexer.cpp"
yy4:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '-':	goto yy221;
		case '=':	goto yy219;
		default:	goto yy5;
		}
yy5:
#line 52 "lexer.re.cpp"
		{ return TokenType::Sub; }
#line 135 "lexer.cpp"
yy6:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy217;
		default:	goto yy7;
		}
yy7:
#line 53 "lexer.re.cpp"
		{ return TokenType::Mul; }
#line 145 "lexer.cpp"
yy8:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy215;
		default:	goto yy9;
		}
yy9:
#line 54 "lexer.re.cpp"
		{ return TokenType::Div; }
#line 155 "lexer.cpp"
yy10:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy213;
		default:	goto yy11;
		}
yy11:
#line 55 "lexer.re.cpp"
		{ return TokenType::Mod; }
#line 165 "lexer.cpp"
yy12:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy209;
		case '|':	goto yy211;
		default:	goto yy13;
		}
yy13:
#line 58 "lexer.re.cpp"
		{ return TokenType::BitwiseOr; }
#line 176 "lexer.cpp"
yy14:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '&':	goto yy207;
		case '=':	goto yy205;
		default:	goto yy15;
		}
yy15:
#line 59 "lexer.re.cpp"
		{ return TokenType::BitwiseAnd; }
#line 187 "lexer.cpp"
yy16:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy203;
		default:	goto yy17;
		}
yy17:
#line 60 "lexer.re.cpp"
		{ return TokenType::BitwiseXor; }
#line 197 "lexer.cpp"
yy18:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '<':	goto yy199;
		case '=':	goto yy197;
		default:	goto yy19;
		}
yy19:
#line 79 "lexer.re.cpp"
		{ return TokenType::LessThan; }
#line 208 "lexer.cpp"
yy20:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy191;
		case '>':	goto yy193;
		default:	goto yy21;
		}
yy21:
#line 81 "lexer.re.cpp"
		{ return TokenType::GreaterThan; }
#line 219 "lexer.cpp"
yy22:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy189;
		default:	goto yy23;
		}
yy23:
#line 65 "lexer.re.cpp"
		{ return TokenType::Assign; }
#line 229 "lexer.cpp"
yy24:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy187;
		default:	goto yy25;
		}
yy25:
#line 66 "lexer.re.cpp"
		{ return TokenType::Negate; }
#line 239 "lexer.cpp"
yy26:
		++p;
#line 83 "lexer.re.cpp"
		{ return TokenType::Question; }
#line 244 "lexer.cpp"
yy28:
		++p;
#line 84 "lexer.re.cpp"
		{ return TokenType::Comma; }
#line 249 "lexer.cpp"
yy30:
		++p;
#line 85 "lexer.re.cpp"
		{ return TokenType::Colon; }
#line 254 "lexer.cpp"
yy32:
		++p;
#line 86 "lexer.re.cpp"
		{ return TokenType::Semicolon; }
#line 259 "lexer.cpp"
yy34:
		++p;
#line 87 "lexer.re.cpp"
		{ return TokenType::LeftParentthesis; }
#line 264 "lexer.cpp"
yy36:
		++p;
#line 88 "lexer.re.cpp"
		{ return TokenType::RightParenthesis; }
#line 269 "lexer.cpp"
yy38:
		++p;
#line 89 "lexer.re.cpp"
		{ return TokenType::LeftSquareBracket; }
#line 274 "lexer.cpp"
yy40:
		++p;
#line 90 "lexer.re.cpp"
		{ return TokenType::RightSquareBracket; }
#line 279 "lexer.cpp"
yy42:
		++p;
#line 91 "lexer.re.cpp"
		{ return TokenType::LeftCurlyBracket; }
#line 284 "lexer.cpp"
yy44:
		++p;
#line 92 "lexer.re.cpp"
		{ return TokenType::RightCurlyBracket; }
#line 289 "lexer.cpp"
yy46:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '1':	goto yy176;
		case '3':	goto yy177;
		case '6':	goto yy178;
		case '8':	goto yy179;
		default:	goto yy76;
		}
yy47:
#line 118 "lexer.re.cpp"
		{ return TokenType::Identifier; }
#line 302 "lexer.cpp"
yy48:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '1':	goto yy165;
		case '3':	goto yy166;
		case '6':	goto yy167;
		case '8':	goto yy168;
		default:	goto yy76;
		}
yy49:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'o':	goto yy161;
		default:	goto yy76;
		}
yy50:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'f':	goto yy159;
		default:	goto yy76;
		}
yy51:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'l':	goto yy155;
		default:	goto yy76;
		}
yy52:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy146;
		case 'o':	goto yy147;
		default:	goto yy76;
		}
yy53:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'h':	goto yy141;
		default:	goto yy76;
		}
yy54:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'o':	goto yy138;
		default:	goto yy76;
		}
yy55:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'a':	goto yy126;
		case 'o':	goto yy127;
		default:	goto yy76;
		}
yy56:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'r':	goto yy121;
		default:	goto yy76;
		}
yy57:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy115;
		default:	goto yy76;
		}
yy58:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 't':	goto yy103;
		case 'w':	goto yy104;
		default:	goto yy76;
		}
yy59:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'o':	goto yy99;
		default:	goto yy76;
		}
yy60:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'y':	goto yy92;
		default:	goto yy76;
		}
yy61:
		++p;
#line 116 "lexer.re.cpp"
		{ return TokenType::EOS; }
#line 391 "lexer.cpp"
yy63:
		++p;
		yych = (unsigned char)*p;
		goto yy91;
yy64:
#line 117 "lexer.re.cpp"
		{ return TokenType::IntegerConstant; }
#line 399 "lexer.cpp"
yy65:
		yych = (unsigned char)*(yymarker = ++p);
		switch (yych) {
		case 'X':
		case 'x':	goto yy77;
		default:	goto yy80;
		}
yy66:
		yych = (unsigned char)*++p;
		goto yy76;
yy67:
		++p;
		yych = (unsigned char)*p;
		goto yy74;
yy68:
#line 121 "lexer.re.cpp"
		{goto initial;}
#line 417 "lexer.cpp"
yy69:
		++p;
#line 123 "lexer.re.cpp"
		{goto initial;}
#line 422 "lexer.cpp"
yy71:
		++p;
#line 124 "lexer.re.cpp"
		{
		printf("unexpected character\n");
		goto initial;
	}
#line 430 "lexer.cpp"
yy73:
		++p;
		yych = (unsigned char)*p;
yy74:
		switch (yych) {
		case '\t':
		case '\v':
		case '\f':
		case ' ':	goto yy73;
		default:	goto yy68;
		}
yy75:
		++p;
		yych = (unsigned char)*p;
yy76:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy47;
		}
yy77:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy88;
		default:	goto yy78;
		}
yy78:
		p = yymarker;
		goto yy64;
yy79:
		++p;
		yych = (unsigned char)*p;
yy80:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':	goto yy79;
		case 'L':	goto yy82;
		case 'U':
		case 'u':	goto yy81;
		case 'l':	goto yy83;
		default:	goto yy64;
		}
yy81:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'L':	goto yy87;
		case 'l':	goto yy86;
		default:	goto yy64;
		}
yy82:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'L':	goto yy84;
		case 'U':
		case 'u':	goto yy85;
		default:	goto yy64;
		}
yy83:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'U':
		case 'u':	goto yy85;
		case 'l':	goto yy84;
		default:	goto yy64;
		}
yy84:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'U':
		case 'u':	goto yy85;
		default:	goto yy64;
		}
yy85:
		yych = (unsigned char)*++p;
		goto yy64;
yy86:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'l':	goto yy85;
		default:	goto yy64;
		}
yy87:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'L':	goto yy85;
		default:	goto yy64;
		}
yy88:
		++p;
		yych = (unsigned char)*p;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy88;
		case 'L':	goto yy82;
		case 'U':
		case 'u':	goto yy81;
		case 'l':	goto yy83;
		default:	goto yy64;
		}
yy90:
		++p;
		yych = (unsigned char)*p;
yy91:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy90;
		case 'L':	goto yy82;
		case 'U':
		case 'u':	goto yy81;
		case 'l':	goto yy83;
		default:	goto yy64;
		}
yy92:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'p':	goto yy93;
		default:	goto yy76;
		}
yy93:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy94;
		default:	goto yy76;
		}
yy94:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'd':	goto yy95;
		default:	goto yy76;
		}
yy95:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy96;
		default:	goto yy76;
		}
yy96:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'f':	goto yy97;
		default:	goto yy76;
		}
yy97:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy98;
		}
yy98:
#line 115 "lexer.re.cpp"
		{ return TokenType::Statement_typedef; }
#line 760 "lexer.cpp"
yy99:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'i':	goto yy100;
		default:	goto yy76;
		}
yy100:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'd':	goto yy101;
		default:	goto yy76;
		}
yy101:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy102;
		}
yy102:
#line 114 "lexer.re.cpp"
		{ return TokenType::Statement_void; }
#line 844 "lexer.cpp"
yy103:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'r':	goto yy110;
		default:	goto yy76;
		}
yy104:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'i':	goto yy105;
		default:	goto yy76;
		}
yy105:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 't':	goto yy106;
		default:	goto yy76;
		}
yy106:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'c':	goto yy107;
		default:	goto yy76;
		}
yy107:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'h':	goto yy108;
		default:	goto yy76;
		}
yy108:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy109;
		}
yy109:
#line 110 "lexer.re.cpp"
		{ return TokenType::Statement_switch; }
#line 946 "lexer.cpp"
yy110:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'u':	goto yy111;
		default:	goto yy76;
		}
yy111:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'c':	goto yy112;
		default:	goto yy76;
		}
yy112:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 't':	goto yy113;
		default:	goto yy76;
		}
yy113:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy114;
		}
yy114:
#line 113 "lexer.re.cpp"
		{ return TokenType::Statement_struct; }
#line 1036 "lexer.cpp"
yy115:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 't':	goto yy116;
		default:	goto yy76;
		}
yy116:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'u':	goto yy117;
		default:	goto yy76;
		}
yy117:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'r':	goto yy118;
		default:	goto yy76;
		}
yy118:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'n':	goto yy119;
		default:	goto yy76;
		}
yy119:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy120;
		}
yy120:
#line 109 "lexer.re.cpp"
		{ return TokenType::Statement_return; }
#line 1132 "lexer.cpp"
yy121:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy122;
		default:	goto yy76;
		}
yy122:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'a':	goto yy123;
		default:	goto yy76;
		}
yy123:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'k':	goto yy124;
		default:	goto yy76;
		}
yy124:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy125;
		}
yy125:
#line 108 "lexer.re.cpp"
		{ return TokenType::Statement_break; }
#line 1222 "lexer.cpp"
yy126:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 's':	goto yy135;
		default:	goto yy76;
		}
yy127:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'n':	goto yy128;
		default:	goto yy76;
		}
yy128:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 't':	goto yy129;
		default:	goto yy76;
		}
yy129:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'i':	goto yy130;
		default:	goto yy76;
		}
yy130:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'n':	goto yy131;
		default:	goto yy76;
		}
yy131:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'u':	goto yy132;
		default:	goto yy76;
		}
yy132:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy133;
		default:	goto yy76;
		}
yy133:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy134;
		}
yy134:
#line 107 "lexer.re.cpp"
		{ return TokenType::Statement_continue; }
#line 1336 "lexer.cpp"
yy135:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy136;
		default:	goto yy76;
		}
yy136:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy137;
		}
yy137:
#line 111 "lexer.re.cpp"
		{ return TokenType::Statement_case; }
#line 1414 "lexer.cpp"
yy138:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'r':	goto yy139;
		default:	goto yy76;
		}
yy139:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy140;
		}
yy140:
#line 106 "lexer.re.cpp"
		{ return TokenType::Statement_for; }
#line 1492 "lexer.cpp"
yy141:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'i':	goto yy142;
		default:	goto yy76;
		}
yy142:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'l':	goto yy143;
		default:	goto yy76;
		}
yy143:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy144;
		default:	goto yy76;
		}
yy144:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy145;
		}
yy145:
#line 105 "lexer.re.cpp"
		{ return TokenType::Statement_while; }
#line 1582 "lexer.cpp"
yy146:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'f':	goto yy149;
		default:	goto yy76;
		}
yy147:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy148;
		}
yy148:
#line 104 "lexer.re.cpp"
		{ return TokenType::Statement_do; }
#line 1660 "lexer.cpp"
yy149:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'a':	goto yy150;
		default:	goto yy76;
		}
yy150:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'u':	goto yy151;
		default:	goto yy76;
		}
yy151:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'l':	goto yy152;
		default:	goto yy76;
		}
yy152:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 't':	goto yy153;
		default:	goto yy76;
		}
yy153:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy154;
		}
yy154:
#line 112 "lexer.re.cpp"
		{ return TokenType::Statement_default; }
#line 1756 "lexer.cpp"
yy155:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 's':	goto yy156;
		default:	goto yy76;
		}
yy156:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'e':	goto yy157;
		default:	goto yy76;
		}
yy157:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy158;
		}
yy158:
#line 103 "lexer.re.cpp"
		{ return TokenType::Statement_else; }
#line 1840 "lexer.cpp"
yy159:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy160;
		}
yy160:
#line 102 "lexer.re.cpp"
		{ return TokenType::Statement_if; }
#line 1912 "lexer.cpp"
yy161:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 't':	goto yy162;
		default:	goto yy76;
		}
yy162:
		yych = (unsigned char)*++p;
		switch (yych) {
		case 'o':	goto yy163;
		default:	goto yy76;
		}
yy163:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy164;
		}
yy164:
#line 101 "lexer.re.cpp"
		{ return TokenType::Statement_goto; }
#line 1996 "lexer.cpp"
yy165:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '6':	goto yy174;
		default:	goto yy76;
		}
yy166:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '2':	goto yy172;
		default:	goto yy76;
		}
yy167:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '4':	goto yy170;
		default:	goto yy76;
		}
yy168:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy169;
		}
yy169:
#line 94 "lexer.re.cpp"
		{ return TokenType::U8; }
#line 2086 "lexer.cpp"
yy170:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy171;
		}
yy171:
#line 100 "lexer.re.cpp"
		{ return TokenType::U64; }
#line 2158 "lexer.cpp"
yy172:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy173;
		}
yy173:
#line 98 "lexer.re.cpp"
		{ return TokenType::U32; }
#line 2230 "lexer.cpp"
yy174:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy175;
		}
yy175:
#line 96 "lexer.re.cpp"
		{ return TokenType::U16; }
#line 2302 "lexer.cpp"
yy176:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '6':	goto yy185;
		default:	goto yy76;
		}
yy177:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '2':	goto yy183;
		default:	goto yy76;
		}
yy178:
		yych = (unsigned char)*++p;
		switch (yych) {
		case '4':	goto yy181;
		default:	goto yy76;
		}
yy179:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy180;
		}
yy180:
#line 93 "lexer.re.cpp"
		{ return TokenType::S8; }
#line 2392 "lexer.cpp"
yy181:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy182;
		}
yy182:
#line 99 "lexer.re.cpp"
		{ return TokenType::S64; }
#line 2464 "lexer.cpp"
yy183:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy184;
		}
yy184:
#line 97 "lexer.re.cpp"
		{ return TokenType::S32; }
#line 2536 "lexer.cpp"
yy185:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy75;
		default:	goto yy186;
		}
yy186:
#line 95 "lexer.re.cpp"
		{ return TokenType::S16; }
#line 2608 "lexer.cpp"
yy187:
		++p;
#line 78 "lexer.re.cpp"
		{ return TokenType::NotEqual; }
#line 2613 "lexer.cpp"
yy189:
		++p;
#line 77 "lexer.re.cpp"
		{ return TokenType::Equal; }
#line 2618 "lexer.cpp"
yy191:
		++p;
#line 82 "lexer.re.cpp"
		{ return TokenType::GreaterThanOrEqual; }
#line 2623 "lexer.cpp"
yy193:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy195;
		default:	goto yy194;
		}
yy194:
#line 64 "lexer.re.cpp"
		{ return TokenType::RightShift; }
#line 2633 "lexer.cpp"
yy195:
		++p;
#line 73 "lexer.re.cpp"
		{ return TokenType::RightShiftAssign; }
#line 2638 "lexer.cpp"
yy197:
		++p;
#line 80 "lexer.re.cpp"
		{ return TokenType::LessThanOrEqual; }
#line 2643 "lexer.cpp"
yy199:
		++p;
		switch ((yych = (unsigned char)*p)) {
		case '=':	goto yy201;
		default:	goto yy200;
		}
yy200:
#line 63 "lexer.re.cpp"
		{ return TokenType::LeftShift; }
#line 2653 "lexer.cpp"
yy201:
		++p;
#line 72 "lexer.re.cpp"
		{ return TokenType::LeftShiftAssign; }
#line 2658 "lexer.cpp"
yy203:
		++p;
#line 75 "lexer.re.cpp"
		{ return TokenType::XorAssign; }
#line 2663 "lexer.cpp"
yy205:
		++p;
#line 74 "lexer.re.cpp"
		{ return TokenType::AndAssign; }
#line 2668 "lexer.cpp"
yy207:
		++p;
#line 62 "lexer.re.cpp"
		{ return TokenType::LogicalAnd; }
#line 2673 "lexer.cpp"
yy209:
		++p;
#line 76 "lexer.re.cpp"
		{ return TokenType::OrAssign; }
#line 2678 "lexer.cpp"
yy211:
		++p;
#line 61 "lexer.re.cpp"
		{ return TokenType::LogicalOr; }
#line 2683 "lexer.cpp"
yy213:
		++p;
#line 71 "lexer.re.cpp"
		{ return TokenType::ModAssign; }
#line 2688 "lexer.cpp"
yy215:
		++p;
#line 70 "lexer.re.cpp"
		{ return TokenType::DivAssign; }
#line 2693 "lexer.cpp"
yy217:
		++p;
#line 69 "lexer.re.cpp"
		{ return TokenType::MulAssign; }
#line 2698 "lexer.cpp"
yy219:
		++p;
#line 68 "lexer.re.cpp"
		{ return TokenType::SubAssign; }
#line 2703 "lexer.cpp"
yy221:
		++p;
#line 57 "lexer.re.cpp"
		{ return TokenType::Decrement; }
#line 2708 "lexer.cpp"
yy223:
		++p;
#line 67 "lexer.re.cpp"
		{ return TokenType::AddAssign; }
#line 2713 "lexer.cpp"
yy225:
		++p;
#line 56 "lexer.re.cpp"
		{ return TokenType::Increment; }
#line 2718 "lexer.cpp"
	}
#line 128 "lexer.re.cpp"

}


